pipeline:
  build:
    image: golang:1.6
    commands:
      - pwd
      - printenv
      - go env
      # - go get github.com/Masterminds/glide
      # - glide install
      - export GOPATH=/drone
      - go env
      - go get
      - go build
      - go test
