pipeline:
  build:
    image: golang:1.6
    commands:
      - export GOPATH=/drone
      - go get -d github.com/Masterminds/glide
      - go install github.com/Masterminds/glide
      - glide install
      - go test
